// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // IMPORTANT: Toutes les configurations pointent maintenant vers le projet erium-ae95f
  // où se trouvent vos données

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UIBLYWk1ZUnN_59g_Xirallt-Xu2me8',
    appId: '1:296950722100:web:9d6b22a9b5fcef190ee461',
    messagingSenderId: '296950722100',
    projectId: 'erium-ae95f',  // ← CHANGÉ de hachaton-dbd9b à erium-ae95f
    authDomain: 'erium-ae95f.firebaseapp.com',  // ← CHANGÉ
    storageBucket: 'erium-ae95f.firebasestorage.app',  // ← CHANGÉ
    measurementId: 'G-7HTR59CPT3',
    databaseURL: 'https://erium-ae95f-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCLdgyGLfHivzr6wxHmYNv6evXn-5Bfb8',
    appId: '1:296950722100:android:fecd35656a2d9f750ee461',
    messagingSenderId: '296950722100',
    projectId: 'erium-ae95f',  // ← CHANGÉ de hachaton-dbd9b à erium-ae95f
    storageBucket: 'erium-ae95f.firebasestorage.app',  // ← CHANGÉ
    databaseURL: 'https://erium-ae95f-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA38czQeNWceKXXEVEqLzDcfSTfAEgWDxg',
    appId: '1:296950722100:ios:44cf6100dd587ed80ee461',
    messagingSenderId: '296950722100',
    projectId: 'erium-ae95f',  // ← CHANGÉ de hachaton-dbd9b à erium-ae95f
    storageBucket: 'erium-ae95f.firebasestorage.app',  // ← CHANGÉ
    iosBundleId: 'fr.erium.erium',
    databaseURL: 'https://erium-ae95f-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA38czQeNWceKXXEVEqLzDcfSTfAEgWDxg',
    appId: '1:296950722100:ios:44cf6100dd587ed80ee461',
    messagingSenderId: '296950722100',
    projectId: 'erium-ae95f',  // ← CHANGÉ de hachaton-dbd9b à erium-ae95f
    storageBucket: 'erium-ae95f.firebasestorage.app',  // ← CHANGÉ
    iosBundleId: 'fr.erium.erium',
    databaseURL: 'https://erium-ae95f-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5UIBLYWk1ZUnN_59g_Xirallt-Xu2me8',
    appId: '1:296950722100:web:7914199fa2eb5d150ee461',
    messagingSenderId: '296950722100',
    projectId: 'erium-ae95f',  // ← CHANGÉ de hachaton-dbd9b à erium-ae95f
    authDomain: 'erium-ae95f.firebaseapp.com',  // ← CHANGÉ
    storageBucket: 'erium-ae95f.firebasestorage.app',  // ← CHANGÉ
    measurementId: 'G-9MZYXSGE88',
    databaseURL: 'https://erium-ae95f-default-rtdb.firebaseio.com',
  );
}